const fs = require('fs');
const path = require('path');

const postsDirectory = path.join(__dirname, '../content');
const outputFilePath = path.join(__dirname, '../lib/blog-posts.ts');

function parseMarkdownFile(fileContent) {
  const match = fileContent.match(/^---\r?\n([\s\S]+?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) {
    return {
      title: '',
      excerpt: '',
      date: '',
      readTime: '',
      tags: [],
      slug: '',
      content: fileContent
    };
  }

  const frontmatterBlock = match[1];
  const content = match[2];

  const metadata = {
    title: '',
    excerpt: '',
    date: '',
    readTime: '',
    tags: [],
    image: ''
  };

  const lines = frontmatterBlock.split(/\r?\n/);
  for (const line of lines) {
    const colonIndex = line.indexOf(':');
    if (colonIndex === -1) continue;

    const key = line.slice(0, colonIndex).trim();
    let value = line.slice(colonIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    if (key === 'tags') {
      try {
        if (value.startsWith('[') && value.endsWith(']')) {
          metadata.tags = JSON.parse(value);
        } else {
          metadata.tags = value.split(',').map(t => t.trim()).filter(Boolean);
        }
      } catch {
        metadata.tags = [];
      }
    } else {
      metadata[key] = value;
    }
  }

  return {
    title: metadata.title,
    excerpt: metadata.excerpt,
    date: metadata.date,
    readTime: metadata.readTime,
    tags: metadata.tags,
    slug: metadata.slug,
    image: metadata.image,
    content: content
  };
}

function generate() {
  if (!fs.existsSync(postsDirectory)) {
    console.error('Directory content/ not found');
    process.exit(1);
  }

  const fileNames = fs.readdirSync(postsDirectory);
  const posts = fileNames
    .filter((fileName) => fileName.endsWith('.md'))
    .map((fileName) => {
      const slug = fileName.replace(/\.md$/, '');
      const fullPath = path.join(postsDirectory, fileName);
      const fileContents = fs.readFileSync(fullPath, 'utf8');
      const parsed = parseMarkdownFile(fileContents);
      
      return {
        slug: parsed.slug || slug,
        title: parsed.title,
        excerpt: parsed.excerpt,
        date: parsed.date,
        readTime: parsed.readTime,
        tags: parsed.tags,
        image: parsed.image || '',
        content: parsed.content
      };
    });

  function parseDate(dateStr) {
    const parts = dateStr.trim().split(/\s+/);
    if (parts.length < 2) return new Date(2026, 0, 1);
    const [monthStr, yearStr] = parts;
    const year = parseInt(yearStr, 10) || 2026;
    const monthMap = {
      Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
      Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
      January: 0, February: 1, March: 2, April: 3, May: 4, June: 5,
      July: 6, August: 7, September: 8, October: 9, November: 10, December: 11
    };
    const month = monthMap[monthStr] !== undefined ? monthMap[monthStr] : 0;
    return new Date(year, month, 1);
  }

  // Pre-sort posts: newest first
  posts.sort((a, b) => parseDate(b.date).getTime() - parseDate(a.date).getTime());

  const tsContent = `// Automatically generated by scripts/generate-posts.js. Do not edit.
export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  date: string
  readTime: string
  content: string
  tags: string[]
  image?: string
}

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)}

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug)
}

export function getAllBlogPosts(): BlogPost[] {
  return blogPosts
}

export const seriesOrder = [
  "seo-prompts-2026",
  "how-search-works-2026",
  "seo-fundamentals",
  "searcher-intent-seo",
  "keyword-research-2026",
  "eeat-google",
  "topical-authority-clusters",
  "ai-writing-for-seo",
  "programmatic-seo",
  "answer-first-writing",
  "technical-seo-crawling-indexing",
  "url-structure-canonicalization",
  "core-web-vitals-2026",
  "ai-crawler-javascript",
  "ai-crawler-robots-txt",
  "hreflang-international-seo",
  "structured-data-essentials",
  "ecommerce-rich-results-schema",
  "answer-engine-optimization",
  "geo-llm-discovery",
  "entity-seo-knowledge-graph",
  "llms-txt",
  "chatgpt-seo",
  "video-seo-youtube",
  "reddit-forum-seo",
  "backlinks-2026",
  "author-authority-seo",
  "topical-authority-strategy",
  "google-search-console-guide",
  "bing-webmaster-tools",
  "indexnow",
  "google-analytics-4-guide",
  "ai-citation-tracking",
  "seo-portfolio-case-study",
  "seo-tools-2026",
  "beyond-google-seo",
  "future-of-search"
]

export function getSortedBlogPosts(): BlogPost[] {
  const chapter0 = blogPosts.find(post => post.slug === "seo-prompts-2026")
  const otherPosts = blogPosts.filter(post => post.slug !== "seo-prompts-2026")
  
  // Convert month/year string to date for sorting
  function parseDate(dateStr: string): Date {
    const parts = dateStr.trim().split(/\\s+/)
    if (parts.length < 2) return new Date(2026, 0, 1)
    
    const [monthStr, yearStr] = parts
    const year = parseInt(yearStr, 10) || 2026
    
    const monthMap: Record<string, number> = {
      Jan: 0, Feb: 1, Mar: 2, Apr: 3, May: 4, Jun: 5,
      Jul: 6, Aug: 7, Sep: 8, Oct: 9, Nov: 10, Dec: 11,
      January: 0, February: 1, March: 2, April: 3, May: 4, June: 5,
      July: 6, August: 7, September: 8, October: 9, November: 10, December: 11
    }
    
    const month = monthMap[monthStr] !== undefined ? monthMap[monthStr] : 0
    return new Date(year, month, 1)
  }

  otherPosts.sort((a, b) => {
    const dateA = parseDate(a.date).getTime()
    const dateB = parseDate(b.date).getTime()
    
    // Different dates: sort by date (newest first)
    if (dateB !== dateA) {
      return dateB - dateA
    }
    
    // Same date: check if both are in series
    const indexA = seriesOrder.indexOf(a.slug)
    const indexB = seriesOrder.indexOf(b.slug)
    
    // Both in series: sort by series order
    if (indexA !== -1 && indexB !== -1) {
      return indexA - indexB
    }
    
    // Only A is in series: B comes first (non-series posts first)
    if (indexA !== -1) return 1
    
    // Only B is in series: A comes first (non-series posts first)
    if (indexB !== -1) return -1
    
    // Neither in series: sort alphabetically by title
    return a.title.localeCompare(b.title)
  })
  
  return chapter0 ? [chapter0, ...otherPosts] : otherPosts
}

export function isSEOSeriesPost(slug: string): boolean {
  return seriesOrder.includes(slug)
}

export function getSEOSeriesNavigation(currentSlug: string): { prev: BlogPost | null, next: BlogPost | null } {
  const currentIndex = seriesOrder.indexOf(currentSlug)
  if (currentIndex === -1) {
    return { prev: null, next: null }
  }
  
  const prevSlug = currentIndex > 0 ? seriesOrder[currentIndex - 1] : null
  const nextSlug = currentIndex < seriesOrder.length - 1 ? seriesOrder[currentIndex + 1] : null
  
  return {
    prev: prevSlug ? getBlogPost(prevSlug) || null : null,
    next: nextSlug ? getBlogPost(nextSlug) || null : null
  }
}
`;

  fs.writeFileSync(outputFilePath, tsContent, 'utf8');
  console.log('Successfully generated lib/blog-posts.ts from markdown files!');

  // Generate public/llms-full.txt (automated citation database for AI engines)
  try {
    const llmsBasePat = path.join(__dirname, '../public/llms.txt');
    const llmsFullPat = path.join(__dirname, '../public/llms-full.txt');
    let llmsBase = '';
    if (fs.existsSync(llmsBasePat)) {
      llmsBase = fs.readFileSync(llmsBasePat, 'utf8');
    } else {
      console.warn('public/llms.txt not found, creating llms-full.txt without base context.');
    }

    let llmsFullContent = llmsBase ? `${llmsBase}\n\n# FULL BLOG ARTICLES DATABASE\n\n` : '# Nabil Thange Blog database\n\n';
    
    // Sort posts oldest to newest or keep series order for logical reading
    const orderedPosts = [...posts].reverse(); // Oldest first to match chronological learning flow
    for (const post of orderedPosts) {
      llmsFullContent += `## ARTICLE: ${post.title}\n`;
      llmsFullContent += `**Slug:** ${post.slug} | **Date:** ${post.date} | **Tags:** ${post.tags.join(', ')}\n\n`;
      llmsFullContent += `${post.content}\n\n---\n\n`;
    }

    fs.writeFileSync(llmsFullPat, llmsFullContent, 'utf8');
    console.log('Successfully generated public/llms-full.txt!');
  } catch (error) {
    console.error('Failed to generate public/llms-full.txt:', error);
  }
}

generate();
